
---

- name: 'Update base installation packages'
  apt:
      update_cache: 'yes'
      upgrade: 'dist'

- name: 'Install tools to support tech stack installation'
  apt:
      name:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'software-properties-common'
          - 'arptables'
          - 'ebtables'
          - 'smartmontools'
      state: 'latest'

